theme: jekyll-theme-minimal
title: Yuki Shiraito
description: Assistant Professor of Political Science, University of Michigan
logo: bayesrule.jpg
show_downloads: false
google_analytics: UA-141734678-1
